'''
Self-contained HTML version of the ethics report.

No external dependencies — all styling is inline. Content is derived
from the JSON report (the source of truth).
'''

import html
import os

RISK_COLORS = {
    "Low": "#2e7d32",     # green
    "Medium": "#f9a825",  # amber
    "High": "#c62828",    # red
}

# Max points per category, mirroring the scoring in analyzer/ethics_report.py
CATEGORY_MAX = {
    "Fairness": 4,
    "Transparency": 2,
    "Privacy": 2,
    "Accountability": 2,
}


def _risk_color(ethics_score):
    for level, color in RISK_COLORS.items():
        if level in ethics_score:
            return color
    return "#616161"


def _list_cards(items, border_color):
    if not items:
        return "<p class='empty'>None</p>"
    cards = []
    for item in items:
        cards.append(
            f"<div class='card' style='border-left: 4px solid {border_color};'>"
            f"{html.escape(str(item))}</div>"
        )
    return "\n".join(cards)


def generate_html_report(report, output_path):
    ethics_score = report.get("ethics_score", "Unknown")
    color = _risk_color(ethics_score)

    score_rows = []
    for category, score in report.get("score_summary", {}).items():
        max_score = CATEGORY_MAX.get(category)
        shown = f"{score}/{max_score}" if max_score else str(score)
        score_rows.append(
            f"<tr><td>{html.escape(category)}</td>"
            f"<td class='num'>{html.escape(shown)}</td></tr>"
        )

    page = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>AIE Ethics Report</title>
<style>
  body {{ font-family: -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
         background: #f5f5f5; color: #212121; margin: 0; padding: 2rem; }}
  .container {{ max-width: 720px; margin: 0 auto; }}
  h1 {{ font-size: 1.4rem; }}
  h2 {{ font-size: 1.1rem; margin-top: 2rem; }}
  .score-card {{ background: {color}; color: white; border-radius: 8px;
                 padding: 1.5rem; text-align: center; font-size: 1.6rem;
                 font-weight: bold; }}
  table {{ border-collapse: collapse; width: 100%; background: white;
           border-radius: 8px; overflow: hidden; }}
  th, td {{ text-align: left; padding: 0.6rem 1rem;
            border-bottom: 1px solid #eeeeee; }}
  td.num {{ text-align: right; font-weight: bold; }}
  .card {{ background: white; border-radius: 6px; padding: 0.8rem 1rem;
           margin-bottom: 0.6rem; box-shadow: 0 1px 2px rgba(0,0,0,0.08); }}
  .empty {{ color: #757575; }}
  footer {{ margin-top: 2rem; color: #757575; font-size: 0.85rem; }}
</style>
</head>
<body>
<div class="container">
  <h1>🕊️ AIE — AI Ethical Analyzer Report</h1>
  <div class="score-card">{html.escape(ethics_score)}</div>

  <h2>Score Breakdown</h2>
  <table>
    <tr><th>Category</th><th style="text-align:right">Score</th></tr>
    {''.join(score_rows)}
  </table>

  <h2>🚩 Red Flags</h2>
  {_list_cards(report.get("red_flags", []), RISK_COLORS["High"])}

  <h2>💡 Recommendations</h2>
  {_list_cards(report.get("recommendations", []), "#1565c0")}

  <footer>Generated by AIE — a first-alert ethical risk scan, not a full fairness audit.</footer>
</div>
</body>
</html>
"""

    out_dir = os.path.dirname(output_path)
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(page)
